### ISSUE TITLE
rfLinkState_timestamp has wrong value typ

### ISSUE THREAD

**Issue by Gundika** [jpgorganizer/ioBroker.smartgarden#39] opened 2022-02-02 19:40 UTC
rfLinkState_timestamp has a wrong value type to get timestamp from gardena mover in ioBroker in date format

**Comment by jpgorganizer** [comment] 2022-02-02 19:45
pls give more info - logs etc.

**Comment by Gundika** [comment] 2022-02-02 20:09
I fixed it by setting value type from string into number :-)
Now it works fine. Thank you for this great ioBroker adapter.

**Comment by jpgorganizer** [comment] 2022-02-02 20:12
ok, but it shouldn't have type string. Could you please just delete the data point. It will be created again by the adapter and then check if it's string or number

**Comment by Gundika** [comment] 2022-02-02 21:08
ok. i did what you wrote. but now there is a meassage invalid date. value tpe is sting now. I manually changed into number and it works fine again

**Comment by jpgorganizer** [comment] 2022-02-02 21:31
thanks - I will re-open the issue, because I should have a look at this

**Comment by Gundika** [comment] 2022-02-02 21:48
> @Gundika : have you switched parameter `pre-define states` ON or OFF?

could please let me know where i could find this parameter? I am really sure that i did not changed this

**Comment by jpgorganizer** [comment] 2022-02-02 22:13
see https://github.com/jpgorganizer/ioBroker.smartgarden#setup-adapter   .....in step 3.2

but it's fine the way it is. It would only be useful for debugging to know how this parameter is set.

**Comment by Gundika** [comment] 2022-02-02 22:28
ah. ok i understand. this parameter is ticked

**Comment by jpgorganizer** [comment] 2022-02-06 09:34
@Gundika

For some reason I hadn't noticed that you got an error on ´rfLinkState_timestamp´. My mind was on a different field. sorry

You then changed the type to number and then the error should be gone? I can't imagine that a String can be written into a Number field.

I'm currently not able to look for the error, because I don't even know what the error is. Please post a log from ioBroker (with loglevel = 3)

**Comment by jpgorganizer** [comment] 2022-04-28 11:44
please give a log for this issue till 30.04.22. otherwise I will close the issue. thanks

**Comment by Gundika** [comment] 2022-05-02 03:34
I changed the type to number and since then  the error is gone.

**Comment by jpgorganizer** [comment] 2022-05-02 10:33
without log not reproducable

**Closed by jpgorganizer** 2022-05-02 10:33 UTC
Labels: bug
